/**
 * Vercel build — set voice mode + bundle single-file widget.
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { spawnSync } from "child_process";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");

const hasInworldKey = !!(process.env.INWORLD_API_KEY || "").trim();
const backend = process.env.VOICE_BACKEND_URL?.trim().replace(/\/$/, "") || null;
const proxy = process.env.VOICE_PROXY_URL?.trim() || null;
const wsUrl =
  proxy ||
  (backend
    ? backend.replace(/^https:/i, "wss:").replace(/^http:/i, "ws:") + "/realtime"
    : null);

const mode = hasInworldKey ? "webrtc" : wsUrl ? "proxy" : "none";

const runtime = {
  mode,
  wsUrl: mode === "proxy" ? wsUrl : null,
  voiceBackend: mode !== "none",
  voiceBackendUrl: backend || null,
  hasInworldKey,
  webrtcConfigUrl: "/api/webrtc-config",
};

fs.writeFileSync(
  path.join(root, "js", "runtime.js"),
  `// Generated by scripts/vercel-build.mjs
window.YUKI_RUNTIME = ${JSON.stringify(runtime, null, 2)};
`
);

const bundle = spawnSync("node", ["scripts/bundle-yuki.mjs"], {
  cwd: root,
  stdio: "inherit",
});

if (bundle.status !== 0) {
  process.exit(bundle.status || 1);
}

console.log("Vercel build OK — voice mode:", mode);
if (mode === "webrtc") console.log("Voice: WebRTC via INWORLD_API_KEY");
else if (mode === "proxy") console.log("Voice: legacy proxy →", wsUrl);
else console.warn("WARNING: set INWORLD_API_KEY on Vercel for voice");
